apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-ssh
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  ssh: {{ .Values.ssh.key | b64enc }}
  known_hosts: {{ .Values.ssh.knownHosts | b64enc }}
