apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters: []
    contexts:
      - name: local
    current-context: local
    preferences: {}
  ankhconfig: |
{{ .Values.ankhconfig | indent 4 }}
