apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-ssh
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  id_rsa: {{ .Values.ssh.id_rsa | b64enc }}
  known_hosts: {{ .Values.ssh.known_hosts | b64enc }}
