# contexts are the different ways in which your ankh files can be deployed to
# kubernetes clusters. Each key in this object is a context and the names can be
# whatever you like.
contexts:
  minikube:
    # kube-context ties this context to a `kubectl` context in your local kube config
    kube-context: minikube
    environment-class: dev
    resource-profile: natural
    release: minikube
    helm-registry-url: https://kubernetes-charts.storage.googleapis.com/
    docker-registry-url: https://registry.docker.io/
    # global can be any nested objects with values that need to be passed to every chart.
    global:
      foo: bar
